import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://valorizzatore-test.mooney.it/val/main_valo.jsp")
    page.locator("input[name=\"j_username\"]").click()
    page.locator("input[name=\"j_password\"]").click()
    page.locator("input[name=\"j_username\"]").click()
    page.locator("input[name=\"j_username\"]").fill("valadmin")
    page.locator("input[name=\"j_password\"]").click()
    page.locator("input[name=\"j_password\"]").fill("valadm")
    page.get_by_role("button", name="LOGIN").click()
    page.get_by_role("link", name="Valorizzazione e Borderò").click()
    page.get_by_role("cell", name="parzialmente elaborato").get_by_role("link").click()
    page.get_by_role("button", name="RI-ELABORA PERIODO").click()
    page.locator("#S_ALL").check()
    page.get_by_role("button", name="AVANTI >>").click()
    page.locator("#STEP div").filter(has_text="seleziona tutto").click()
    page.locator("#S_ALL").check()
    page.get_by_role("button", name="AVANTI >>").click()
    page.get_by_role("button", name="LANCIA PROCESSO").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page.get_by_role("button", name="AGGIORNA MONITOR").click()
    page1 = context.new_page()
    page1.goto("https://login.microsoftonline.com/e757ecc5-f28a-4050-8d90-d9bae0391066/oauth2/v2.0/authorize?client_id=cf684cdf-a14d-404d-bb94-f743d0adf4f5&scope=User.Read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Fnts-test.mooney.it%2Fdashboard&client-request-id=0196c4f1-e6d5-738d-a0c8-555a83d8bc08&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=3.28.1&client_info=1&code_challenge=lPjTfaCXpKSfz3-YGs63d3SCInnLnNZArfFim2ftTos&code_challenge_method=S256&nonce=0196c4f1-e6d6-7dc1-ae50-363f78a41612&state=eyJpZCI6IjAxOTZjNGYxLWU2ZDUtNzQzZi1hMTRhLWZkNDY0MWJjZTcyYSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&sso_reload=true")
    page1.get_by_role("textbox", name="Immettere un indirizzo di").click()
    page1.get_by_role("textbox", name="Immettere un indirizzo di").fill("dbt.super.user@mooney.it")
    page1.get_by_role("button", name="Avanti").click()
    page1.goto("https://nts-test.mooney.it/dashboard/")
    page1.get_by_label("Plafond").locator("path").click()
    page1.get_by_role("heading", name="Periodi Contabili").click()
    page1.locator("body").press("ControlOrMeta+-")
    page1.locator("body").press("ControlOrMeta+-")
    page1.locator("body").press("ControlOrMeta+-")
    page1.get_by_text("Gestione periodi contabiliId").click()
    page1.get_by_role("gridcell", name="Edit Delete").get_by_label("Edit").click()
    page1.get_by_text("INSERITO").click()
    page1.get_by_role("option", name="UFFICIALE").click()
    page1.get_by_role("menuitem", name="Save").click()
    page1.get_by_role("row", name="1194 12/05/2025 18/05/2025 05").get_by_label("Edit").click()
    page1.get_by_text("VALORIZZATO").click()
    page1.get_by_role("option", name="VERIFICATO").click()
    page1.get_by_role("menuitem", name="Save").click()
    page1.get_by_role("button", name="Inserisci").click()
    page1.get_by_role("button", name="Scegli la data, la data selezionata è 26 mag").click()
    page1.get_by_role("gridcell", name="31", exact=True).click()
    page1.get_by_role("menuitem", name="Save").click()
    page.get_by_role("link", name="Valorizzazione e Borderò").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)